# Design System Standards

>
> Auto-generated by Bridge OS
> Source: {{EXPORT_PATH}}
> Last sync: {{TIMESTAMP}}
>
> ⚠️ Do not edit this file manually — run `.bridge-os/sync.sh` to update.

---

## Rules for the Agent

1. **Tokens only** — Never hardcode color, spacing, or typography values.
   Always use the CSS variables defined in the tokens table below.
2. **Use exported components** — If a component exists in `design-export/components/`,
   import and use it. Do not re-implement it.
3. **Check user flows first** — Before implementing any screen, read
   `design-export/user-flows.md` to understand the correct sequence and states.
4. **Shell is the layout** — The app shell from `design-export/components/Shell/`
   wraps all sections. Do not create custom layout wrappers.
5. **No new components without a spec** — If a component doesn't exist in
   `design-export/`, stop and ask before creating it.

---

## Design Tokens

### Colors

| Token | Value | Description |
|-------|-------|-------------|
{{TOKENS_COLORS}}

### Typography

| Token | Value |
|-------|-------|
{{TOKENS_TYPOGRAPHY}}

### Spacing

| Token | Value |
|-------|-------|
{{TOKENS_SPACING}}

---

## Available Components

The following components are exported in `design-export/components/`.
**Import them — do not recreate them.**

{{COMPONENTS}}

---

## Design OS Reference Files

| File | When to use |
|------|-------------|
| `design-export/one-shot-prompt.md` | Full implementation in one session |
| `design-export/section-prompt.md` | Implement section by section |
| `design-export/user-flows.md` | Understand navigation and screen states |
| `design-export/test-specs.md` | Define test cases |
| `design-export/product-requirements.md` | Product context and requirements |